[project]
name = 'Blockchain-Based-Marine-Ecosystem-Protection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.conservation-funding]
path = 'contracts/conservation-funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.ecosystem-monitoring]
path = 'contracts/ecosystem-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.fishing-regulation]
path = 'contracts/fishing-regulation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
